### PR TITLE
Fix  typo

### PR DESCRIPTION
**Pull request by shuheiktgw**
Sorry, it just caught my eyes...

### CODE REVIEW

**Comment by AndrewPrifer** [comment]
Haha I must have spaced out. 😄

**Comment by shuheiktgw** [comment]
Haha, thanks! BTW, I actually stole (let's put it "I'm inspired by") your implementation and am trying to build a gem. I'm thinking about releasing it but is it ok for you?

Here is the repository.
https://github.com/shuheiktgw/tinder_auth_fetcher/blob/master/lib/tinder_auth_fetcher.rb

Of course, I'm going to mention this gem is based on your repository in README if you would let release it. So let me know what do you think. 😄 

Thanks!

**Comment by AndrewPrifer** [comment]
Of course it's okay! The original idea came from some guy on /r/tinder anyway. 😄

**Comment by shuheiktgw** [comment]
Hi Andrew, so sorry for my freaking tardy response. I just officially released [the library](https://github.com/shuheiktgw/tinder_auth_fetcher/) Thank you!! 👍

**Pull request merged**
